name: Build and Publish NuGet Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'  # Adjust the version as needed

    - name: Build
      run: dotnet build -c Release src/Clients/AngelOne.SmartApi.Clients.csproj

    - name: Pack
      run: dotnet pack -c Release --no-build src/Clients/AngelOne.SmartApi.Clients.csproj

  publish:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Clear NuGet Cache
      run: dotnet nuget locals all --clear

    - name: Download NuGet CLI
      run: |
        wget https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
        chmod +x nuget.exe

    - name: Push NuGet Package
      run: |
        mono nuget.exe push ./src/Clients/bin/Release/*.nupkg -Source https://api.nuget.org/v3/index.json -ApiKey ${{ secrets.NUGET_API_KEY }}
